/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Blackhole_ring_0: THREE.Mesh
    Blackhole_ring2_0: THREE.Mesh
    Blackhole_skin_0: THREE.Mesh
    Blackhole_skin_inner_0: THREE.Mesh
  }
  materials: {
    Blackhole_ring: THREE.MeshStandardMaterial
    Blackhole_ring2: THREE.MeshStandardMaterial
    Blackhole_skin: THREE.MeshStandardMaterial
    Blackhole_skin_inner: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Blackhole_ring_0.geometry} material={materials.Blackhole_ring} />
      <mesh geometry={nodes.Blackhole_ring2_0.geometry} material={materials.Blackhole_ring2} />
      <mesh geometry={nodes.Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
      <mesh geometry={nodes.Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')